from typing import List, Dict, Any, Tuple, Optional, Set

from src.context.base_context import ExecutionContext
from src.core.constants import DEFAULT_WORKSPACE_ARTIFACTS
from src.players.configs import PLAYER_CONFIGS
from src.tools.base import resolve_toolsets


def validate_plan_dataflow(
    plan: List[Dict[str, Any]],
    initial_artifacts: Optional[Set[str]] = None
) -> Tuple[bool, str]:
    """
    Validates the dataflow dependencies of a generated plan.

    It checks that for every step, the required input artifacts have been
    produced by a previous step in the plan or are pre-populated in the workspace.
    This prevents the agent from starting a plan with logical errors in its dataflow.

    Args:
        plan: The list of step dictionaries, as generated by the planner.
        initial_artifacts: Optional set of artifact names already in workspace.
                          Defaults to DEFAULT_WORKSPACE_ARTIFACTS.

    Returns:
        A tuple containing a boolean (True if valid, False if invalid) and a
        status message.
    """
    # Start with pre-populated workspace artifacts
    if initial_artifacts is None:
        initial_artifacts = DEFAULT_WORKSPACE_ARTIFACTS
    produced_artifacts = set(initial_artifacts)
    
    for i, step in enumerate(plan):
        # Check the inputs required by the current step
        for param, artifact_name in step.get("inputs", {}).items():
            if artifact_name not in produced_artifacts:
                error_msg = (
                    f"Validation Error in Step {i+1} ('{step['task']}'): "
                    f"Input '{param}' requires artifact '{artifact_name}', "
                    "which is not produced by any preceding step."
                )
                return (False, error_msg)
        
        # Register the outputs of the current step for subsequent steps to use
        for artifact_name in step.get("outputs", []):
            # Optional: You could add a check here for duplicate artifact names
            # if you want to enforce that every artifact name is unique.
            produced_artifacts.add(artifact_name)
            
    return (True, "Plan dataflow is valid.")


def validate_plan_tool_compatibility(
    plan: List[Dict[str, Any]],
    context: ExecutionContext,
    allowed_players: Optional[Set[str]] = None,
) -> Tuple[bool, str]:
    """
    Validate that planned players are usable against the given context.

    Checks:
    - The planned player exists in PLAYER_CONFIGS.
    - The planned player is in the allowed player pool (if provided).
    - If a player requests toolsets, at least one resolves for this context.
      (Players intentionally configured with zero toolsets are allowed.)
    """
    errors: List[str] = []

    for i, step in enumerate(plan):
        player_name = step.get("player", "")
        task_name = step.get("task", "<unknown>")

        if player_name not in PLAYER_CONFIGS:
            errors.append(
                f"Step {i+1} ('{task_name}') uses unknown player '{player_name}'."
            )
            continue

        if allowed_players is not None and player_name not in allowed_players:
            errors.append(
                f"Step {i+1} ('{task_name}') uses player '{player_name}' "
                "which is not in the effective player pool."
            )
            continue

        requested = PLAYER_CONFIGS[player_name].get("toolsets", [])
        if requested and not resolve_toolsets(requested, context):
            errors.append(
                f"Step {i+1} ('{task_name}') uses player '{player_name}' but none of its "
                f"toolsets {requested} resolve for a "
                f"'{context.context_type.value}' context."
            )

    if errors:
        return False, " | ".join(errors)

    return True, "Plan tool compatibility is valid."


# Column arguments leak into a step's ``inputs`` under these suffixes
# (``lat_column``, ``lon_column``, ``time_column``, ``spatial_columns``, ...).
_COLUMN_KEY_SUFFIXES = ("_column", "_columns", "_col", "_cols")


def _looks_like_column_param(key: str) -> bool:
    return key.lower().endswith(_COLUMN_KEY_SUFFIXES)


def _context_columns(context: ExecutionContext) -> Set[str]:
    """Lower-cased column names across every tabular resource in the context."""
    columns: Set[str] = set()
    for info in context.get_all_resource_info().values():
        for name in getattr(info, "field_names", None) or []:
            columns.add(str(name).lower())
    return columns


def validate_plan_columns(
    plan: List[Dict[str, Any]],
    context: ExecutionContext,
) -> Tuple[bool, str]:
    """Reject a plan that references a column the data does not contain.

    Planners sometimes invent column names (``latitude``, ``longitude``,
    ``timestamp``) when a standard asks for information a dataset cannot provide.
    Such a column surfaces as a step-input value under a ``*_column`` key.

    A value under such a key is flagged only when it is **neither** a real column
    of some resource **nor** an artifact produced by a step. The second exclusion
    matters: a key like ``spatial_columns`` can carry the *artifact* output of a
    prior detection step (legitimate dataflow wiring), and whether that artifact
    resolves in order is the dataflow validator's job, not this one's. This check
    is strictly about *invented columns* — values that name nothing at all.

    Matching is case-insensitive and lenient across resources: a column is valid
    if it exists in *any* resource, so a mistaken ``target_resources`` never
    causes a false rejection.
    """
    real_columns = _context_columns(context)

    produced_artifacts = set(DEFAULT_WORKSPACE_ARTIFACTS)
    for step in plan:
        produced_artifacts.update(step.get("outputs", []))

    errors: List[str] = []
    for i, step in enumerate(plan):
        task_name = step.get("task", "<unknown>")
        for key, value in step.get("inputs", {}).items():
            if not _looks_like_column_param(key):
                continue
            candidates = value if isinstance(value, list) else str(value).split(",")
            for col in (c.strip() for c in candidates):
                if not col:
                    continue
                if col.lower() in real_columns:
                    continue  # a real column — fine
                if col in produced_artifacts:
                    continue  # an artifact reference — dataflow's concern, not ours
                errors.append(
                    f"Step {i+1} ('{task_name}') references column '{col}' via "
                    f"'{key}', which is neither a column of any resource nor an "
                    "artifact produced by a step."
                )

    if errors:
        return False, " | ".join(errors)

    return True, "Plan column references are valid."
