from typing import List, Dict, Any, Tuple, Optional, Set

from src.context.base_context import ContextType
from src.players.configs import PLAYER_CONFIGS
from src.tools.context_tools import filter_tools_by_context_type

# Pre-populated artifacts available in the workspace at execution start
DEFAULT_WORKSPACE_ARTIFACTS = {
    "metadata_standard",
    "_context_key",
    "_context_info", 
    "_schema",
}

def validate_plan_dataflow(
    plan: List[Dict[str, Any]],
    initial_artifacts: Optional[Set[str]] = None
) -> Tuple[bool, str]:
    """
    Validates the dataflow dependencies of a generated plan.

    It checks that for every step, the required input artifacts have been
    produced by a previous step in the plan or are pre-populated in the workspace.
    This prevents the agent from starting a plan with logical errors in its dataflow.

    Args:
        plan: The list of step dictionaries, as generated by the planner.
        initial_artifacts: Optional set of artifact names already in workspace.
                          Defaults to DEFAULT_WORKSPACE_ARTIFACTS.

    Returns:
        A tuple containing a boolean (True if valid, False if invalid) and a
        status message.
    """
    # Start with pre-populated workspace artifacts
    if initial_artifacts is None:
        initial_artifacts = DEFAULT_WORKSPACE_ARTIFACTS
    produced_artifacts = set(initial_artifacts)
    
    for i, step in enumerate(plan):
        # Check the inputs required by the current step
        for param, artifact_name in step.get("inputs", {}).items():
            if artifact_name not in produced_artifacts:
                error_msg = (
                    f"Validation Error in Step {i+1} ('{step['task']}'): "
                    f"Input '{param}' requires artifact '{artifact_name}', "
                    "which is not produced by any preceding step."
                )
                return (False, error_msg)
        
        # Register the outputs of the current step for subsequent steps to use
        for artifact_name in step.get("outputs", []):
            # Optional: You could add a check here for duplicate artifact names
            # if you want to enforce that every artifact name is unique.
            produced_artifacts.add(artifact_name)
            
    return (True, "Plan dataflow is valid.")


def validate_plan_tool_compatibility(
    plan: List[Dict[str, Any]],
    context_type: ContextType,
    allowed_players: Optional[Set[str]] = None,
) -> Tuple[bool, str]:
    """
    Validate that planned players are usable in the given context type.

    Checks:
    - The planned player exists in PLAYER_CONFIGS.
    - The planned player is in the allowed player pool (if provided).
    - If a player has configured tools, at least one tool is compatible with context_type.
      (Players intentionally configured with zero tools are allowed.)
    """
    errors: List[str] = []

    for i, step in enumerate(plan):
        player_name = step.get("player", "")
        task_name = step.get("task", "<unknown>")

        if player_name not in PLAYER_CONFIGS:
            errors.append(
                f"Step {i+1} ('{task_name}') uses unknown player '{player_name}'."
            )
            continue

        if allowed_players is not None and player_name not in allowed_players:
            errors.append(
                f"Step {i+1} ('{task_name}') uses player '{player_name}' "
                "which is not in the effective player pool."
            )
            continue

        configured_tools = PLAYER_CONFIGS[player_name].get("tools", [])
        compatible_tools = filter_tools_by_context_type(configured_tools, context_type)
        if configured_tools and not compatible_tools:
            errors.append(
                f"Step {i+1} ('{task_name}') uses player '{player_name}' but none of its "
                f"tools are compatible with context type '{context_type.value}'."
            )

    if errors:
        return False, " | ".join(errors)

    return True, "Plan tool compatibility is valid."
